### ISSUE TITLE
Create ZCTA2000 -> PCSA2010 crosswalk

### ISSUE THREAD

**Issue by austensen** [austensen/capstone#3]
__Prep files (Maxwell)__
- [x] Get 2000 ZCTA shapefiles
- [x] Get PCSA V3.1 shapefiles (2010)
- [x] Get 2000 Block shapefiles
- [x] Get 2000 Block population

__Perform Spatial Join (@ganzamy)__
- [x] Overlay ZCTAs, PCSAs and Blocks
- [x] For each block assign a ZCTA (if >=50% covered)
- [x] For each block assign a PCSA (if >=50% covered)

__Construct allocation factors/final crosswalk file (@gnarsim)__ (see `xwalk_example.R`)
- [x] Merge block population into dataset (?)
- [x] By ZCTA sum block populations, for total ZCTA population
- [x] By ZCTA and PCSA, sum block population and divide by ZCTA population
- [x] By ZCTA sum block populations

**Comment by austensen** [comment]
NYC Block Populations:
/Users/Maxwell/Dropbox/capstone/data/raw/block_pop/block2000_pop.csv

All shapefiles are here:
/Users/Maxwell/Dropbox/capstone/gis/nycb2000_16c/

ZCTA and PCSA are for all US but block are just NYC (and clipped to shoreline). I don't think we need to worry so much about clipping the ZCTAs or PCSAs.

**Comment by ganzamy** [comment]
The completed crosswalk is located in the capstone dropbox folder. 
Note: I took the the zcta/pcsa with the maximum share of a census tract instead of at least 50% since some did not have a clear majority. This only affected a small number of them since most had a large share in one zcta/pcsa.

**Comment by austensen** [comment]
Later today I will create the R script for creating the final crosswalk, and get it started by joining the data Amy created with the block-level population. Then I can hand it off to @gnarsim to finish the rest of those steps.

**Comment by austensen** [comment]
@gnarsim, are you merging in the block populations or are you wanting me to do that?

**Comment by gnarsim** [comment]
@austensen I can merge the block populations.

**Comment by gnarsim** [comment]
@austensen I can't find the population file in the dropbox, was it moved somewhere else?

**Comment by austensen** [comment]
@ganzamy, did you keep all those files you removed fromdropbox to save space? Would you be able to add the block population back in? 
I'm out now, but once I'm back I can re download load it. 
Or, @gnarsim you can download it. It's from NHGIS. Just get 2000 block population. You'll have to set up a free account.

**Comment by gnarsim** [comment]
@austensen @ganzamy I can download the data, will let you guys know if I have any issues with it.

**Comment by ganzamy** [comment]
oh no! I'm so sorry. I moved the data folder back into the shared folder. I didn't realize it had the pop data in it. Sorry!

**Comment by gnarsim** [comment]
Got it, thanks Amy!

**Comment by austensen** [comment]
Hey @gnarsim, have you made the R script for this crosswalk yet? I don't see it in github, did you forget to sync maybe? 
I just wanted to check some things with picking up geographies that aren't in NYC, and it would be helpful to be able to go through the steps of making the crosswalk. 
Thanks

**Comment by gnarsim** [comment]
@austensen sorry it doesn't seem to have synced. I don't have my laptop with me, but will make sure it is up this evening.

**Comment by austensen** [comment]
No problem, it's not a rush or anything. Thanks

**Comment by austensen** [comment]
Hey @gnarsim , can you add your crosswalk code. thanks

**Comment by austensen** [comment]
I finished with the crosswalk creation. I fixed some of the issues created by missing values from a variety of sources, and I've also removed all the PCSAs that extend outside of NYC (into long island and westchester). The new crosswalk is `"../Dropbox/capstone/zcta00_pcsa10_xwalk.csv"`
