### ISSUE TITLE
final PCSA-level health indicators

### ISSUE THREAD

**Issue by austensen** [austensen/capstone#5]
- [x] download ZCTA-level raw data (JD)
- [x] crosswalk ZCTAs to PCSAs (MA) 
- [x] re-create all health indicators from raw variables for 2010 (JD)
- [x] create health indicators from raw 1999-2000 data (JD)
- [x] merge in PCSA-level gentrification status indicator (MA)

**Comment by austensen** [comment]
Hey @jdolatshahi, 
I'm working on doing this and realized that the order of this should really be to do some basic cleaning of the all the variables in the raw zcta-level data, then do the geography merge, then finish the cleaning. For example, all the missing values need to be dealt with first, and it would be nice to drop all the variables we don't need before doing the geography crosswalk. 

Do you already have code for doing this cleaning for the variables that I can use on the zcta-level data before I do the crosswalk?

**Comment by jdolatshahi** [comment]
@austensen I was using the same kind of code I used last time. Something like this: 
dart_fem <-
  dart_raw2 %>%
  transmute(pcsa = pcsa,
    pcsa_l = pcsa_l,
    fem15_44 = pp12i30 + pp12i31 + pp12i32 + pp12i33 + pp12i34 + pp12i36 + pp12i37 + pp12i38
  ) %>%
    mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .)))

Do you need something like this for all the variables in the older data?

**Comment by austensen** [comment]
Thanks, sorry I just saw that you already had that and it's actually pretty simple. I just used that last part.

```
mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .)))
```

I'll let you know when I've got it ready at the PCSA2010-level.

**Comment by austensen** [comment]
I've done the crosswalk for the 1999 data from zcta to pcsa2010 geographies. Once we have all the final variables created for these health data files we can merge that and the gentrification indicators and census variables.

**Comment by jdolatshahi** [comment]
I have all the indicators created for 99-01 and 2010 PCSAs. In trying to figure out the issue with the ED rates, I realized we may not have the denominator we need to calculate the ED rate. We do have the correct denom for PCP visits and hospital discharges for 2010.
